name: Secret Demo

on: [push]

jobs:
  secret-job:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar Secret
        env:
          MY_API_KEY: ${{ secrets.API_KEY }}
        run: |
          if [ -z "$MY_API_KEY" ]; then
            echo "API_KEY não encontrada!"
          else
            echo "API_KEY configurado"
          fi